"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import type { LessonObject } from "@/lib/curriculum";
import type { MisconceptionObject } from "@/lib/eedi";
import type { OutputPackage } from "@/lib/mock-outputs";

interface OutputPanelProps {
  output: OutputPackage;
  lesson: LessonObject;
  misconception: MisconceptionObject;
  onReset: () => void;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  return (
    <button
      onClick={handleCopy}
      className="text-xs text-muted-foreground transition-colors hover:text-foreground"
    >
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

interface OutputCardProps {
  label: string;
  number: number;
  content: string;
  source: string;
  accent?: string;
}

function OutputCard({ label, number, content, source, accent = "" }: OutputCardProps) {
  return (
    <Card className="border-border bg-card p-5">
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="flex items-center gap-2">
          <span className="flex h-5 w-5 items-center justify-center rounded-full bg-muted font-mono text-xs text-muted-foreground">
            {number}
          </span>
          <p className={`text-xs font-semibold uppercase tracking-wider ${accent || "text-muted-foreground"}`}>
            {label}
          </p>
        </div>
        <CopyButton text={content} />
      </div>
      <p className="text-sm leading-relaxed text-foreground/90">{content}</p>
      <p className="mt-3 text-xs text-muted-foreground/60 font-mono">
        Source: {source}
      </p>
    </Card>
  );
}

export function OutputPanel({
  output,
  lesson,
  misconception,
  onReset,
}: OutputPanelProps) {
  const allText = `# Cool-Down Studio — Output Package
**Lesson:** ${lesson.lesson_id}: ${lesson.title}
**Misconception:** ${misconception.label} (${misconception.misconception_id})
**Standard:** ${lesson.standard_id}

---

## 1. Re-Assessment Question
${output.reAssessmentQuestion}

*Source: ${output.sources.reAssessment}*

## 2. Feedback Stem for Returned Papers
${output.feedbackStem}

*Source: ${output.sources.feedback}*

## 3. Tomorrow's Warm-Up
${output.warmUp}

*Source: ${output.sources.warmUp}*

## 4. IM Curriculum Connection
${output.imConnection}

*Source: ${output.sources.connection}*

---
Generated by IM Cool-Down Studio · Grounded in Illustrative Mathematics G6 Unit 2 + Eedi Misconception Taxonomy`;

  const [allCopied, setAllCopied] = useState(false);

  async function handleCopyAll() {
    await navigator.clipboard.writeText(allText);
    setAllCopied(true);
    setTimeout(() => setAllCopied(false), 1800);
  }

  return (
    <div className="space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="space-y-0.5">
          <p className="text-sm font-medium">Output Package Ready</p>
          <div className="flex items-center gap-1.5">
            <Badge variant="outline" className="font-mono text-xs text-muted-foreground">
              {misconception.misconception_id}
            </Badge>
            <span className="text-xs text-muted-foreground">
              {misconception.label}
            </span>
          </div>
        </div>
        <button
          onClick={onReset}
          className="text-xs text-muted-foreground transition-colors hover:text-foreground"
        >
          Start over
        </button>
      </div>

      <Separator />

      {/* Output cards */}
      <OutputCard
        number={1}
        label="Re-Assessment Question"
        content={output.reAssessmentQuestion}
        source={output.sources.reAssessment}
        accent="text-blue-400"
      />
      <OutputCard
        number={2}
        label="Feedback Stem for Returned Papers"
        content={output.feedbackStem}
        source={output.sources.feedback}
        accent="text-violet-400"
      />
      <OutputCard
        number={3}
        label="Tomorrow's Warm-Up"
        content={output.warmUp}
        source={output.sources.warmUp}
        accent="text-emerald-400"
      />
      <OutputCard
        number={4}
        label="IM Curriculum Connection"
        content={output.imConnection}
        source={output.sources.connection}
        accent="text-amber-400"
      />

      {/* Copy all */}
      <Button
        variant="outline"
        onClick={handleCopyAll}
        className="w-full"
      >
        {allCopied ? "Copied to clipboard" : "Copy all as markdown"}
      </Button>
    </div>
  );
}
