"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Annotation } from "@/components/annotation";
import type { LessonObject } from "@/lib/curriculum";
import type { MisconceptionObject } from "@/lib/eedi";
import type { OutputPackage } from "@/lib/mock-outputs";

interface OutputPanelProps {
  output: OutputPackage;
  lesson: LessonObject;
  misconception: MisconceptionObject;
  onReset: () => void;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  return (
    <button
      onClick={handleCopy}
      className="text-xs text-muted-foreground transition-colors hover:text-[--il-purple]"
    >
      {copied ? "Copied ✓" : "Copy"}
    </button>
  );
}

const cardAccents = [
  {
    label: "Re-Assessment Question",
    labelNode: (
      <Annotation
        tooltip="A new problem that checks the same skill as yesterday's cool-down. Students who corrected their thinking should get this right. Use it tomorrow or later in the week."
        side="top"
      >
        Re-Assessment Question
      </Annotation>
    ),
    accentClass: "border-l-blue-500",
    labelClass: "text-blue-700",
    bgClass: "bg-blue-50/50",
  },
  {
    label: "Feedback Stem for Returned Papers",
    labelNode: (
      <Annotation
        tooltip="A sentence starter to write on returned work. It names the exact reasoning error and points toward the correct approach — more useful than 'see me' or 'check your work.'"
        side="top"
      >
        Feedback Stem for Returned Papers
      </Annotation>
    ),
    accentClass: "border-l-violet-500",
    labelClass: "text-violet-700",
    bgClass: "bg-violet-50/50",
  },
  {
    label: "Tomorrow's Warm-Up",
    labelNode: (
      <Annotation
        tooltip="A 5–10 minute activity to open the next class. It either revisits yesterday's gap (for students who struggled) or bridges to new content (for students who got it). Designed for whole-class use."
        side="top"
      >
        Tomorrow's Warm-Up
      </Annotation>
    ),
    accentClass: "border-l-emerald-500",
    labelClass: "text-emerald-700",
    bgClass: "bg-emerald-50/50",
  },
  {
    label: "IM Curriculum Connection",
    labelNode: (
      <Annotation
        tooltip="Where this reasoning gap lives in the Illustrative Mathematics sequence — the specific upcoming lesson or unit that addresses it. Helps you know how much reteaching to do now vs. letting the curriculum handle it."
        side="top"
      >
        IM Curriculum Connection
      </Annotation>
    ),
    accentClass: "border-l-amber-500",
    labelClass: "text-amber-700",
    bgClass: "bg-amber-50/50",
  },
];

interface OutputCardProps {
  number: number;
  content: string;
  source: string;
  accent: (typeof cardAccents)[number];
}

function OutputCard({ number, content, source, accent }: OutputCardProps) {
  return (
    <Card
      className={`border border-border border-l-4 ${accent.accentClass} ${accent.bgClass} p-5 ai-glow-border`}
      style={{ boxShadow: "var(--il-glow-sm)" }}
    >
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="flex items-center gap-2">
          <span className="flex h-5 w-5 items-center justify-center rounded-full bg-white border border-border font-mono text-xs text-muted-foreground">
            {number}
          </span>
          <p className={`text-xs font-semibold uppercase tracking-wider ${accent.labelClass}`}>
            {accent.labelNode ?? accent.label}
          </p>
        </div>
        <CopyButton text={content} />
      </div>
      <p className="text-sm leading-relaxed text-foreground/90">{content}</p>
      <p className="mt-3 text-xs text-muted-foreground/60 font-mono">
        Source: {source}
      </p>
    </Card>
  );
}

export function OutputPanel({
  output,
  lesson,
  misconception,
  onReset,
}: OutputPanelProps) {
  const [allCopied, setAllCopied] = useState(false);

  const allText = `# Cool-Down Studio — Output Package
**Lesson:** ${lesson.lesson_id}: ${lesson.title}
**Misconception:** ${misconception.label} (${misconception.misconception_id})
**Standard:** ${lesson.standard_id}

---

## 1. Re-Assessment Question
${output.reAssessmentQuestion}

*Source: ${output.sources.reAssessment}*

## 2. Feedback Stem for Returned Papers
${output.feedbackStem}

*Source: ${output.sources.feedback}*

## 3. Tomorrow's Warm-Up
${output.warmUp}

*Source: ${output.sources.warmUp}*

## 4. IM Curriculum Connection
${output.imConnection}

*Source: ${output.sources.connection}*

---
Generated by IM Cool-Down Studio · Grounded in Illustrative Mathematics G6 Unit 2 + Eedi Misconception Taxonomy`;

  async function handleCopyAll() {
    await navigator.clipboard.writeText(allText);
    setAllCopied(true);
    setTimeout(() => setAllCopied(false), 1800);
  }

  const outputContents = [
    { content: output.reAssessmentQuestion, source: output.sources.reAssessment },
    { content: output.feedbackStem, source: output.sources.feedback },
    { content: output.warmUp, source: output.sources.warmUp },
    { content: output.imConnection, source: output.sources.connection },
  ];

  return (
    <div className="space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="space-y-0.5">
          <div className="flex items-center gap-2">
            {/* AI indicator */}
            <div
              className="flex items-center gap-1.5 rounded-full border border-[--il-purple-border] bg-[--il-purple-muted] px-2.5 py-0.5"
              style={{ boxShadow: "var(--il-glow-sm)" }}
            >
              <div className="h-1.5 w-1.5 rounded-full bg-[--il-purple] animate-pulse" />
              <span className="text-xs font-medium text-[--il-purple]">
                AI output ready
              </span>
            </div>
          </div>
          <div className="flex items-center gap-1.5 mt-1">
            <Badge
              variant="outline"
              className="font-mono text-xs border-[--il-purple-border] text-[--il-purple] bg-[--il-purple-muted]"
            >
              {misconception.misconception_id}
            </Badge>
            <span className="text-xs text-muted-foreground">
              {misconception.label}
            </span>
          </div>
        </div>
        <button
          onClick={onReset}
          className="text-xs text-muted-foreground transition-colors hover:text-[--il-purple]"
        >
          Start over
        </button>
      </div>

      <Separator />

      {/* Output cards */}
      {outputContents.map((item, i) => (
        <OutputCard
          key={i}
          number={i + 1}
          content={item.content}
          source={item.source}
          accent={cardAccents[i]}
        />
      ))}

      {/* Copy all */}
      <Button
        variant="outline"
        onClick={handleCopyAll}
        className="w-full border-[--il-purple-border] text-[--il-purple] hover:bg-[--il-purple-muted]"
      >
        {allCopied ? "Copied to clipboard ✓" : "Copy all as markdown"}
      </Button>
    </div>
  );
}
