"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { CLUSTER_WARMUPS, CLUSTER_META } from "@/lib/mock-students";

type ActionableCluster = "M_RP_003" | "M_RP_001" | "M_RP_009";
const CLUSTERS: ActionableCluster[] = ["M_RP_003", "M_RP_001", "M_RP_009"];

interface ApproveCTAProps {
  approvedClusters: Record<ActionableCluster, boolean>;
  unclassifiedAssignments: Record<string, ActionableCluster | null>;
  unclassifiedCount: number;
}

export function ApproveCTA({
  approvedClusters,
  unclassifiedAssignments,
  unclassifiedCount,
}: ApproveCTAProps) {
  const [pushed, setPushed] = useState(false);
  const [markdownCopied, setMarkdownCopied] = useState(false);

  const approvedCount = CLUSTERS.filter((id) => approvedClusters[id]).length;
  const assignedCount = Object.values(unclassifiedAssignments).filter(Boolean).length;
  const allReady =
    approvedCount === CLUSTERS.length && assignedCount === unclassifiedCount;

  const markdownOutput = CLUSTERS.filter((id) => approvedClusters[id])
    .map((id) => {
      const warmup = CLUSTER_WARMUPS[id];
      const meta = CLUSTER_META[id];
      return `## ${meta.label} (${id})\n\n**Tomorrow's warm-up:**\n${warmup.question}\n\n*Source: ${warmup.source}*`;
    })
    .join("\n\n---\n\n");

  async function handleCopyAll() {
    await navigator.clipboard.writeText(
      `# Cool-Down Studio — Mode 2 Output\n\nG6 Unit 2 Lesson 1 · ${new Date().toLocaleDateString()}\n\n---\n\n${markdownOutput}\n\n---\nGenerated by IM Cool-Down Studio`
    );
    setMarkdownCopied(true);
    setTimeout(() => setMarkdownCopied(false), 1800);
  }

  function handlePush() {
    setPushed(true);
  }

  if (pushed) {
    return (
      <div
        className="rounded-xl border border-[--il-purple-border] bg-[--il-purple-muted] p-6 text-center space-y-2"
        style={{ boxShadow: "var(--il-glow-md)" }}
      >
        <div className="flex items-center justify-center gap-2">
          <div className="h-2 w-2 rounded-full bg-[--il-purple] animate-pulse" />
          <p className="text-sm font-semibold text-[--il-purple]">
            Differentiated warm-ups pushed to tomorrow's lesson
          </p>
        </div>
        <p className="text-xs text-muted-foreground">
          Each student group will see their personalized question at the start of class.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-border bg-white p-5 space-y-4">
      {/* Summary */}
      <div className="space-y-1">
        <p className="text-sm font-semibold text-foreground">Ready to push?</p>
        <div className="flex flex-col gap-1">
          <div className="flex items-center gap-2 text-xs">
            <span className={approvedCount === CLUSTERS.length ? "text-emerald-600" : "text-muted-foreground"}>
              {approvedCount === CLUSTERS.length ? "✓" : "○"}
            </span>
            <span className={approvedCount === CLUSTERS.length ? "text-foreground" : "text-muted-foreground"}>
              {approvedCount} of {CLUSTERS.length} cluster warm-ups approved
            </span>
          </div>
          <div className="flex items-center gap-2 text-xs">
            <span className={assignedCount === unclassifiedCount ? "text-emerald-600" : "text-muted-foreground"}>
              {assignedCount === unclassifiedCount ? "✓" : "○"}
            </span>
            <span className={assignedCount === unclassifiedCount ? "text-foreground" : "text-muted-foreground"}>
              {assignedCount} of {unclassifiedCount} unclassified responses assigned
            </span>
          </div>
        </div>
      </div>

      {/* CTAs */}
      <div className="flex flex-col gap-2">
        <Button
          onClick={handlePush}
          disabled={!allReady}
          className="w-full"
          size="lg"
          style={allReady ? { boxShadow: "var(--il-glow-md)" } : {}}
        >
          Push differentiated warm-ups to tomorrow's lesson
        </Button>

        <Button
          variant="outline"
          onClick={handleCopyAll}
          disabled={approvedCount === 0}
          className="w-full border-[--il-purple-border] text-[--il-purple] hover:bg-[--il-purple-muted]"
        >
          {markdownCopied ? "Copied ✓" : "Copy all as markdown"}
        </Button>
      </div>

      {!allReady && (
        <p className="text-xs text-muted-foreground text-center">
          {approvedCount < CLUSTERS.length
            ? `Approve all ${CLUSTERS.length} cluster warm-ups to continue.`
            : `Assign all ${unclassifiedCount} unclassified response${unclassifiedCount !== 1 ? "s" : ""} to continue.`}
        </p>
      )}
    </div>
  );
}
